### PR TITLE
fixed responsive header

### LINKED ISSUE #11: Add header responsive
**Is your feature request related to a problem? Please describe.**
The header of the website is not responsive yet.

Can you provide a solution for it?

### PR DESCRIPTION
**Pull request by Augs0**
Makes header more responsive in relation to #11 
Header now moves between column and row layout between breakpoints. Achieved through mix of flexbox and tweaking padding that had been implemented.

### CODE REVIEW

**Review by RafaelGSS — CHANGES_REQUESTED** [review]
Thanks for submitting the PR.

Seems that this change affects the header title, can you fix it?
image

**Comment by Augs0** [comment]
Sure @RafaelGSS can you clarify what you mean by affecting the header title? In other words, what is the desired result?

**Comment by Augs0** [comment]
I noticed the about section goes over the header past a certain point because it's set to position:absolute. I thought about removing it to solve the problem, but I wasn't sure if this was intended behaviour?

**Review by RafaelGSS — APPROVED** [review]
LGTM. Fix the conflict to land :tada:

**Comment by Augs0** [comment]
Great, thanks for the feedback. LMK if you ever want help proofreading an English version in the future (even post-Hacktober :D) I don't speak Portuguese, but happy to help with English checks 👍

**Comment by RafaelGSS** [comment]
> Great, thanks for the feedback. LMK if you ever want help proofreading an English version in the future (even post-Hacktober :D) I don't speak Portuguese, but happy to help with English checks

Of course, We are planning an i18n version.

**Pull request merged**
