### PR TITLE
updated header styles

### PR DESCRIPTION
**Pull request by SafaElmali**

### CODE REVIEW

**Review by RafaelGSS — CHANGES_REQUESTED** [review]
Can you adjust access lint check?

**Comment by SafaElmali** [comment]
> Can you adjust access lint check?

Sure!

**Comment by RafaelGSS** [comment]
Thanks for contributing, but the new header is not based on [our design from figma](https://www.figma.com/file/yP5HlDYmfsOYlwMLs0Ou4q/Acess?node-id=0%3A1). 

Maybe you can help us adding a responsive header?

**Comment by SafaElmali** [comment]
> Thanks for contributing, but the new header is not based on [our design from figma](https://www.figma.com/file/yP5HlDYmfsOYlwMLs0Ou4q/Acess?node-id=0%3A1).
> 
> Maybe you can help us adding a responsive header?

Sure. I will do my best!

**Comment by SafaElmali** [comment]
> Thanks for contributing, but the new header is not based on [our design from figma](https://www.figma.com/file/yP5HlDYmfsOYlwMLs0Ou4q/Acess?node-id=0%3A1).
> 
> Maybe you can help us adding a responsive header?

Can I use add Bootstrap library to make it responsive?

**Comment by SafaElmali** [comment]
> Thanks for contributing, but the new header is not based on [our design from figma](https://www.figma.com/file/yP5HlDYmfsOYlwMLs0Ou4q/Acess?node-id=0%3A1).
> 
> Maybe you can help us adding a responsive header?

Can I use Bootstrap library?

**Comment by RafaelGSS** [comment]
Can I use Bootstrap library?

Sure, not cdn if possible

**Comment by RafaelGSS** [comment]
> Can I use Bootstrap library?

I think so

**Review by RafaelGSS — CHANGES_REQUESTED** [review]
Can you fix the conflicts and use Bootstrap from node_modules without cdn?

**Comment by SafaElmali** [comment]
> Can you fix the conflicts and use Bootstrap from node_modules without cdn?

Sure. I will check it out

**Comment by SafaElmali** [comment]
I am using bootstrap css from node_modules but for some JS files, I put them below the body tag. Is this a problem?

**Comment by SafaElmali** [comment]
I think you already solved this issue? :) Should I continue to make changes ? :)

**Comment by RafaelGSS** [comment]
Your brach is conflicting with master yet :( Can solve? After it, I can pull your branch to see :smile:

**Review by yuresilva — CHANGES_REQUESTED** [review]
Hello, according to your pull request, we saw that it is out of date.
Today the project already has new things ready, which I would recommend
It would give the master a git pull to capture all changes made to the project. Where you will have a task of leaving only responsive Header link for mobile, which the rest of the site is already responsive.

**Pull request closed without merging**
